### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by stevenaproctor** [mrkwrght/A11y-patterns#6]
The ">" is being read out loud by NVDA on Firefox. There is no need to read this out. You can either add them as a background image that is ignored by screen readers or surround them with an aria-hidden="true".

Use aria-current="true" for the page you are currently on.

**Comment by philsherry** [comment]
Is this _really_ an ordered list? (I'm suggesting it's not.)

You should be able to account for every single character that you commit. Those characters should also validate. 

```
<ul class="list">
  <li><a href="#breadcrumb">Breadcrumbs</a></li>
  <li><a href="#navbar">Navigation bars</a></li>
<ul>
</ul></ul>
```

**Comment by philsherry** [comment]
`GET https://markwright785.github.io/A11YPatterns/assets/css/assets/images/breadcrumb.png 404 (Not Found)`
